# Semana 1: Comparación de Frameworks para Cómputo Numérico y Tensorial
## Notebook de Ejercicios (NB2) - NumPy, PyTorch, TensorFlow, JAX

### Propósito de la sesión
En este notebook llevaremos los conceptos matemáticos (escalares, vectores, matrices, tensores) a la práctica utilizando los principales frameworks de IA: **NumPy**, **PyTorch**, **TensorFlow** y **JAX**. Compararemos su sintaxis, realizaremos operaciones básicas y mediremos el rendimiento en CPU y GPU (si está disponible).

### Objetivos de aprendizaje
*   Representar y operar con escalares, vectores, matrices y tensores en NumPy, PyTorch, TensorFlow y JAX.
*   Comparar la sintaxis y las convenciones de cada framework.
*   Medir el tiempo de ejecución de operaciones intensivas (multiplicación de matrices, etc.) en CPU y GPU.
*   Entender la importancia de la aceleración por hardware en el entrenamiento de modelos de IA.
*   Aplicar funciones de activación y pérdida sobre tensores en diferentes frameworks.

## Configuración Inicial

Primero, importamos las librerías necesarias y verificamos la disponibilidad de GPU en el entorno (especialmente importante para PyTorch, TensorFlow y JAX).

**Nota para Google Colab:** Para usar GPU, ve a `Entorno de ejecución` -> `Cambiar tipo de entorno de ejecución` y selecciona `GPU`. Luego ejecuta esta celda para confirmar.

In [1]:
#!pip install --upgrade pip
#!pip install --upgrade "jax[cuda12]"

In [2]:
#import jax
#print(jax.devices())

In [3]:
# Frameworks principales
import numpy as np
import torch
import tensorflow as tf
import jax
import jax.numpy as jnp

# Para medición de tiempos
import time

# Verificar versiones
print("NumPy versión:", np.__version__)
print("PyTorch versión:", torch.__version__)
print("TensorFlow versión:", tf.__version__)
print("JAX versión:", jax.__version__)

# Verificar disponibilidad de GPU
print("\n--- Disponibilidad de GPU ---")
print("PyTorch GPU disponible?", torch.cuda.is_available())
if torch.cuda.is_available():
    print("  PyTorch GPU:", torch.cuda.get_device_name(0))

print("TensorFlow GPU disponible?", tf.config.list_physical_devices('GPU'))

print("JAX GPU disponible?", jax.devices())  # Debería mostrar 'gpu' si está disponible

# Configuración para JAX (usar 64-bit para precisión doble, opcional)
jax.config.update("jax_enable_x64", True)

NumPy versión: 2.0.2
PyTorch versión: 2.10.0+cu128
TensorFlow versión: 2.19.0
JAX versión: 0.9.1

--- Disponibilidad de GPU ---
PyTorch GPU disponible? True
  PyTorch GPU: Tesla T4
TensorFlow GPU disponible? [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
JAX GPU disponible? [CudaDevice(id=0)]


---
## Parte 1: Operaciones Básicas con Escalares, Vectores, Matrices y Tensores

En esta sección crearemos los mismos objetos matemáticos en cada framework y realizaremos operaciones fundamentales. Esto te ayudará a familiarizarte con la sintaxis de cada uno.

### 1.1 Escalares

Un escalar es simplemente un número. En NumPy es un array de 0 dimensiones; en PyTorch y TensorFlow es un tensor con 0 dimensiones; en JAX es un array escalar.

In [4]:
# NumPy
a_np = np.array(5.2)
b_np = np.array(3.0)
print("NumPy:", a_np, "+", b_np, "=", a_np + b_np)

# PyTorch
a_pt = torch.tensor(5.2)
b_pt = torch.tensor(3.0)
print("PyTorch:", a_pt, "+", b_pt, "=", a_pt + b_pt)

# TensorFlow
a_tf = tf.constant(5.2)
b_tf = tf.constant(3.0)
print("TensorFlow:", a_tf.numpy(), "+", b_tf.numpy(), "=", (a_tf + b_tf).numpy())

# JAX
a_jax = jnp.array(5.2)
b_jax = jnp.array(3.0)
print("JAX:", a_jax, "+", b_jax, "=", a_jax + b_jax)

NumPy: 5.2 + 3.0 = 8.2
PyTorch: tensor(5.2000) + tensor(3.) = tensor(8.2000)
TensorFlow: 5.2 + 3.0 = 8.2
JAX: 5.2 + 3.0 = 8.2


### 1.2 Vectores

Un vector es un array de una dimensión. Lo creamos y luego calculamos la suma, el producto punto y la norma.

In [5]:
# Datos comunes
data1 = [1.0, 2.0, 3.0]
data2 = [4.0, 5.0, 6.0]

# NumPy
v1_np = np.array(data1)
v2_np = np.array(data2)
print("NumPy:")
print("  v1 =", v1_np, "v2 =", v2_np)
print("  suma =", v1_np + v2_np)
print("  producto punto =", np.dot(v1_np, v2_np))
print("  norma L2 de v1 =", np.linalg.norm(v1_np))

# PyTorch
v1_pt = torch.tensor(data1)
v2_pt = torch.tensor(data2)
print("\nPyTorch:")
print("  suma =", v1_pt + v2_pt)
print("  producto punto =", torch.dot(v1_pt, v2_pt))
print("  norma L2 de v1 =", torch.norm(v1_pt))

# TensorFlow
v1_tf = tf.constant(data1)
v2_tf = tf.constant(data2)
print("\nTensorFlow:")
print("  suma =", (v1_tf + v2_tf).numpy())
print("  producto punto =", tf.tensordot(v1_tf, v2_tf, axes=1).numpy())
print("  norma L2 de v1 =", tf.norm(v1_tf).numpy())

# JAX
v1_jax = jnp.array(data1)
v2_jax = jnp.array(data2)
print("\nJAX:")
print("  suma =", v1_jax + v2_jax)
print("  producto punto =", jnp.dot(v1_jax, v2_jax))
print("  norma L2 de v1 =", jnp.linalg.norm(v1_jax))

NumPy:
  v1 = [1. 2. 3.] v2 = [4. 5. 6.]
  suma = [5. 7. 9.]
  producto punto = 32.0
  norma L2 de v1 = 3.7416573867739413

PyTorch:
  suma = tensor([5., 7., 9.])
  producto punto = tensor(32.)
  norma L2 de v1 = tensor(3.7417)

TensorFlow:
  suma = [5. 7. 9.]
  producto punto = 32.0
  norma L2 de v1 = 3.7416573

JAX:
  suma = [5. 7. 9.]
  producto punto = 32.0
  norma L2 de v1 = 3.7416573867739413


### 1.3 Matrices

Una matriz es un array de dos dimensiones. Realizaremos suma, multiplicación elemento a elemento y multiplicación matricial.

In [6]:
# Datos comunes
mat1 = [[1, 2], [3, 4]]
mat2 = [[5, 6], [7, 8]]

# NumPy
m1_np = np.array(mat1)
m2_np = np.array(mat2)
print("NumPy:")
print("  m1:\n", m1_np)
print("  m2:\n", m2_np)
print("  suma:\n", m1_np + m2_np)
print("  producto elemento a elemento:\n", m1_np * m2_np)
print("  multiplicación matricial (m1 @ m2):\n", m1_np @ m2_np)

# PyTorch
m1_pt = torch.tensor(mat1)
m2_pt = torch.tensor(mat2)
print("\nPyTorch:")
print("  suma:\n", m1_pt + m2_pt)
print("  producto elemento a elemento:\n", m1_pt * m2_pt)
print("  multiplicación matricial (m1 @ m2):\n", m1_pt @ m2_pt)

# TensorFlow
m1_tf = tf.constant(mat1)
m2_tf = tf.constant(mat2)
print("\nTensorFlow:")
print("  suma:\n", (m1_tf + m2_tf).numpy())
print("  producto elemento a elemento:\n", (m1_tf * m2_tf).numpy())
print("  multiplicación matricial (matmul):\n", tf.matmul(m1_tf, m2_tf).numpy())

# JAX
m1_jax = jnp.array(mat1)
m2_jax = jnp.array(mat2)
print("\nJAX:")
print("  suma:\n", m1_jax + m2_jax)
print("  producto elemento a elemento:\n", m1_jax * m2_jax)
print("  multiplicación matricial (jnp.dot):\n", jnp.dot(m1_jax, m2_jax))

NumPy:
  m1:
 [[1 2]
 [3 4]]
  m2:
 [[5 6]
 [7 8]]
  suma:
 [[ 6  8]
 [10 12]]
  producto elemento a elemento:
 [[ 5 12]
 [21 32]]
  multiplicación matricial (m1 @ m2):
 [[19 22]
 [43 50]]

PyTorch:
  suma:
 tensor([[ 6,  8],
        [10, 12]])
  producto elemento a elemento:
 tensor([[ 5, 12],
        [21, 32]])
  multiplicación matricial (m1 @ m2):
 tensor([[19, 22],
        [43, 50]])

TensorFlow:
  suma:
 [[ 6  8]
 [10 12]]
  producto elemento a elemento:
 [[ 5 12]
 [21 32]]
  multiplicación matricial (matmul):
 [[19 22]
 [43 50]]

JAX:
  suma:
 [[ 6  8]
 [10 12]]
  producto elemento a elemento:
 [[ 5 12]
 [21 32]]
  multiplicación matricial (jnp.dot):
 [[19 22]
 [43 50]]


### 1.4 Tensores 3D

Un tensor de tres dimensiones puede verse como una pila de matrices. Por ejemplo, un lote de 2 matrices de 3x3.

In [7]:
# Datos: dos matrices 3x3
tensor_data = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
]

# NumPy
t_np = np.array(tensor_data)
print("NumPy:")
print("  shape:", t_np.shape)
print("  primer elemento (matriz 0):\n", t_np[0])

# PyTorch
t_pt = torch.tensor(tensor_data)
print("\nPyTorch:")
print("  shape:", t_pt.shape)

# TensorFlow
t_tf = tf.constant(tensor_data)
print("\nTensorFlow:")
print("  shape:", t_tf.shape)

# JAX
t_jax = jnp.array(tensor_data)
print("\nJAX:")
print("  shape:", t_jax.shape)

NumPy:
  shape: (2, 3, 3)
  primer elemento (matriz 0):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

PyTorch:
  shape: torch.Size([2, 3, 3])

TensorFlow:
  shape: (2, 3, 3)

JAX:
  shape: (2, 3, 3)


---
## Parte 2: Medición de Rendimiento (CPU vs GPU)

Ahora compararemos el tiempo de ejecución de una operación costosa (multiplicación de matrices grandes) en cada framework, tanto en CPU como en GPU (si está disponible). Esto te dará una idea de la importancia de la aceleración por hardware.

**Nota:** En Colab, asegúrate de haber activado la GPU en el menú `Entorno de ejecución` antes de ejecutar esta sección.

### 2.1 Multiplicación de matrices grandes (2000 x 2000)

Crearemos dos matrices aleatorias de tamaño 2000x2000 y mediremos el tiempo que tarda su multiplicación.

In [8]:
size = 2000

# NumPy (siempre CPU)
A_np = np.random.randn(size, size).astype(np.float32)
B_np = np.random.randn(size, size).astype(np.float32)

start = time.time()
C_np = A_np @ B_np
end = time.time()
print(f"NumPy (CPU): {end - start:.4f} seg")

# PyTorch (CPU)
A_pt_cpu = torch.tensor(A_np)
B_pt_cpu = torch.tensor(B_np)
start = time.time()
C_pt_cpu = A_pt_cpu @ B_pt_cpu
end = time.time()
print(f"PyTorch (CPU): {end - start:.4f} seg")

# PyTorch (GPU) si está disponible
if torch.cuda.is_available():
    A_pt_gpu = torch.tensor(A_np).cuda()
    B_pt_gpu = torch.tensor(B_np).cuda()
    # Calentamiento (warm up) para evitar medición con compilación inicial
    for _ in range(3):
        _ = A_pt_gpu @ B_pt_gpu
    torch.cuda.synchronize()
    start = time.time()
    C_pt_gpu = A_pt_gpu @ B_pt_gpu
    torch.cuda.synchronize()
    end = time.time()
    print(f"PyTorch (GPU): {end - start:.4f} seg")
else:
    print("PyTorch (GPU): no disponible")

# TensorFlow (CPU)
A_tf_cpu = tf.constant(A_np)
B_tf_cpu = tf.constant(B_np)
start = time.time()
C_tf_cpu = tf.matmul(A_tf_cpu, B_tf_cpu)
end = time.time()
print(f"TensorFlow (CPU): {end - start:.4f} seg")

# TensorFlow (GPU) si está disponible
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    with tf.device('/GPU:0'):
        A_tf_gpu = tf.constant(A_np)
        B_tf_gpu = tf.constant(B_np)
        # Calentamiento
        for _ in range(3):
            _ = tf.matmul(A_tf_gpu, B_tf_gpu)
        start = time.time()
        C_tf_gpu = tf.matmul(A_tf_gpu, B_tf_gpu)
        end = time.time()
    print(f"TensorFlow (GPU): {end - start:.4f} seg")
else:
    print("TensorFlow (GPU): no disponible")

# JAX (CPU) - JAX por defecto usa CPU si no hay GPU visible
A_jax_cpu = jnp.array(A_np)
B_jax_cpu = jnp.array(B_np)
start = time.time()
C_jax_cpu = jnp.dot(A_jax_cpu, B_jax_cpu)
end = time.time()
print(f"JAX (CPU): {end - start:.4f} seg")

# JAX (GPU) si está disponible
if any('gpu' in str(d).lower() for d in jax.devices()):
    # JAX usualmente usa GPU automáticamente si está presente
    A_jax_gpu = jnp.array(A_np)
    B_jax_gpu = jnp.array(B_np)
    # Calentamiento
    for _ in range(3):
        _ = jnp.dot(A_jax_gpu, B_jax_gpu)
    start = time.time()
    C_jax_gpu = jnp.dot(A_jax_gpu, B_jax_gpu)
    end = time.time()
    print(f"JAX (GPU): {end - start:.4f} seg")
else:
    print("JAX (GPU): no disponible")

print("\n¡Nota la gran diferencia de velocidad cuando se usa GPU!")

NumPy (CPU): 0.1953 seg
PyTorch (CPU): 0.2462 seg
PyTorch (GPU): 0.0062 seg
TensorFlow (CPU): 0.0010 seg
TensorFlow (GPU): 0.0001 seg
JAX (CPU): 0.3310 seg
JAX (GPU): no disponible

¡Nota la gran diferencia de velocidad cuando se usa GPU!


---
## Parte 3: Funciones de Activación y Pérdida con Tensores

En esta sección aplicaremos funciones de activación y pérdida sobre tensores que representan lotes de datos. Esto simula lo que ocurre en una red neuronal.

### 3.1 Funciones de Activación

Definimos un tensor de entrada (por ejemplo, un lote de 1000 muestras con 10 características) y aplicamos sigmoide, ReLU, tanh en cada framework.

In [9]:
batch_size = 1000
features = 10

# Generar datos aleatorios (usaremos los mismos para todos)
np.random.seed(42)
data_np = np.random.randn(batch_size, features).astype(np.float32)

# NumPy
print("NumPy:")
x_np = data_np
start = time.time()
y_sig_np = 1 / (1 + np.exp(-x_np))
y_relu_np = np.maximum(0, x_np)
y_tanh_np = np.tanh(x_np)
end = time.time()
print(f"  Tiempo total activaciones: {end - start:.6f} seg")

# PyTorch (CPU)
x_pt = torch.from_numpy(data_np)
start = time.time()
y_sig_pt = torch.sigmoid(x_pt)
y_relu_pt = torch.relu(x_pt)
y_tanh_pt = torch.tanh(x_pt)
end = time.time()
print(f"PyTorch (CPU): {end - start:.6f} seg")

# PyTorch (GPU) si disponible
if torch.cuda.is_available():
    x_pt_gpu = torch.from_numpy(data_np).cuda()
    # Calentamiento
    for _ in range(3):
        _ = torch.sigmoid(x_pt_gpu)
    torch.cuda.synchronize()
    start = time.time()
    y_sig_pt_gpu = torch.sigmoid(x_pt_gpu)
    y_relu_pt_gpu = torch.relu(x_pt_gpu)
    y_tanh_pt_gpu = torch.tanh(x_pt_gpu)
    torch.cuda.synchronize()
    end = time.time()
    print(f"PyTorch (GPU): {end - start:.6f} seg")

# TensorFlow (CPU)
x_tf = tf.constant(data_np)
start = time.time()
y_sig_tf = tf.sigmoid(x_tf)
y_relu_tf = tf.nn.relu(x_tf)
y_tanh_tf = tf.tanh(x_tf)
end = time.time()
print(f"TensorFlow (CPU): {end - start:.6f} seg")

# TensorFlow (GPU) si disponible
if gpus:
    with tf.device('/GPU:0'):
        x_tf_gpu = tf.constant(data_np)
        # Calentamiento
        for _ in range(3):
            _ = tf.sigmoid(x_tf_gpu)
        start = time.time()
        y_sig_tf_gpu = tf.sigmoid(x_tf_gpu)
        y_relu_tf_gpu = tf.nn.relu(x_tf_gpu)
        y_tanh_tf_gpu = tf.tanh(x_tf_gpu)
        end = time.time()
    print(f"TensorFlow (GPU): {end - start:.6f} seg")

# JAX (CPU)
x_jax = jnp.array(data_np)
start = time.time()
y_sig_jax = jax.nn.sigmoid(x_jax)
y_relu_jax = jax.nn.relu(x_jax)
y_tanh_jax = jnp.tanh(x_jax)
end = time.time()
print(f"JAX (CPU): {end - start:.6f} seg")

# JAX (GPU) si disponible
if any('gpu' in str(d).lower() for d in jax.devices()):
    x_jax_gpu = jnp.array(data_np)
    # Calentamiento
    for _ in range(3):
        _ = jax.nn.sigmoid(x_jax_gpu)
    start = time.time()
    y_sig_jax_gpu = jax.nn.sigmoid(x_jax_gpu)
    y_relu_jax_gpu = jax.nn.relu(x_jax_gpu)
    y_tanh_jax_gpu = jnp.tanh(x_jax_gpu)
    end = time.time()
    print(f"JAX (GPU): {end - start:.6f} seg")
else:
    print("JAX (GPU): no disponible")

NumPy:
  Tiempo total activaciones: 0.001070 seg
PyTorch (CPU): 0.020324 seg
PyTorch (GPU): 0.045141 seg
TensorFlow (CPU): 0.148698 seg
TensorFlow (GPU): 0.000248 seg
JAX (CPU): 0.139296 seg
JAX (GPU): no disponible


### 3.2 Funciones de Pérdida

Calcularemos la pérdida MSE y la entropía cruzada binaria para un batch de predicciones y etiquetas.

In [10]:
# Datos sintéticos: predicciones (logits) y etiquetas
np.random.seed(123)
batch_size = 1000
num_classes = 10

# Para MSE: regresión
y_true_reg = np.random.randn(batch_size, 1).astype(np.float32)
y_pred_reg = np.random.randn(batch_size, 1).astype(np.float32)

# Para BCE: clasificación binaria
y_true_bin = np.random.randint(0, 2, size=(batch_size, 1)).astype(np.float32)
y_pred_bin = np.random.rand(batch_size, 1).astype(np.float32)  # probabilidades

print("Calculando pérdidas...")

# NumPy
start = time.time()
mse_np = np.mean((y_true_reg - y_pred_reg)**2)
# BCE con estabilidad numérica
eps = 1e-7
y_pred_bin_clip = np.clip(y_pred_bin, eps, 1 - eps)
bce_np = -np.mean(y_true_bin * np.log(y_pred_bin_clip) + (1 - y_true_bin) * np.log(1 - y_pred_bin_clip))
end = time.time()
print(f"NumPy: MSE={mse_np:.6f}, BCE={bce_np:.6f}, tiempo={end - start:.6f} seg")

# PyTorch (CPU)
y_true_reg_pt = torch.from_numpy(y_true_reg)
y_pred_reg_pt = torch.from_numpy(y_pred_reg)
y_true_bin_pt = torch.from_numpy(y_true_bin)
y_pred_bin_pt = torch.from_numpy(y_pred_bin)

start = time.time()
mse_pt = torch.mean((y_true_reg_pt - y_pred_reg_pt)**2)
bce_pt = torch.nn.functional.binary_cross_entropy(y_pred_bin_pt, y_true_bin_pt)
end = time.time()
print(f"PyTorch (CPU): MSE={mse_pt.item():.6f}, BCE={bce_pt.item():.6f}, tiempo={end - start:.6f} seg")

# PyTorch (GPU) si disponible
if torch.cuda.is_available():
    y_true_reg_pt_gpu = torch.from_numpy(y_true_reg).cuda()
    y_pred_reg_pt_gpu = torch.from_numpy(y_pred_reg).cuda()
    y_true_bin_pt_gpu = torch.from_numpy(y_true_bin).cuda()
    y_pred_bin_pt_gpu = torch.from_numpy(y_pred_bin).cuda()
    # Calentamiento
    for _ in range(3):
        _ = torch.mean((y_true_reg_pt_gpu - y_pred_reg_pt_gpu)**2)
        _ = torch.nn.functional.binary_cross_entropy(y_pred_bin_pt_gpu, y_true_bin_pt_gpu)
    torch.cuda.synchronize()
    start = time.time()
    mse_pt_gpu = torch.mean((y_true_reg_pt_gpu - y_pred_reg_pt_gpu)**2)
    bce_pt_gpu = torch.nn.functional.binary_cross_entropy(y_pred_bin_pt_gpu, y_true_bin_pt_gpu)
    torch.cuda.synchronize()
    end = time.time()
    print(f"PyTorch (GPU): MSE={mse_pt_gpu.item():.6f}, BCE={bce_pt_gpu.item():.6f}, tiempo={end - start:.6f} seg")

# TensorFlow (CPU)
y_true_reg_tf = tf.constant(y_true_reg)
y_pred_reg_tf = tf.constant(y_pred_reg)
y_true_bin_tf = tf.constant(y_true_bin)
y_pred_bin_tf = tf.constant(y_pred_bin)

start = time.time()
mse_tf = tf.reduce_mean((y_true_reg_tf - y_pred_reg_tf)**2)
bce_tf = tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_true_bin_tf, y_pred_bin_tf))
end = time.time()
print(f"TensorFlow (CPU): MSE={mse_tf.numpy():.6f}, BCE={bce_tf.numpy():.6f}, tiempo={end - start:.6f} seg")

# TensorFlow (GPU) si disponible
if gpus:
    with tf.device('/GPU:0'):
        y_true_reg_tf_gpu = tf.constant(y_true_reg)
        y_pred_reg_tf_gpu = tf.constant(y_pred_reg)
        y_true_bin_tf_gpu = tf.constant(y_true_bin)
        y_pred_bin_tf_gpu = tf.constant(y_pred_bin)
        # Calentamiento
        for _ in range(3):
            _ = tf.reduce_mean((y_true_reg_tf_gpu - y_pred_reg_tf_gpu)**2)
            _ = tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_true_bin_tf_gpu, y_pred_bin_tf_gpu))
        start = time.time()
        mse_tf_gpu = tf.reduce_mean((y_true_reg_tf_gpu - y_pred_reg_tf_gpu)**2)
        bce_tf_gpu = tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_true_bin_tf_gpu, y_pred_bin_tf_gpu))
        end = time.time()
    print(f"TensorFlow (GPU): MSE={mse_tf_gpu.numpy():.6f}, BCE={bce_tf_gpu.numpy():.6f}, tiempo={end - start:.6f} seg")

# JAX (CPU)
y_true_reg_jax = jnp.array(y_true_reg)
y_pred_reg_jax = jnp.array(y_pred_reg)
y_true_bin_jax = jnp.array(y_true_bin)
y_pred_bin_jax = jnp.array(y_pred_bin)

def mse_jax(y_true, y_pred):
    return jnp.mean((y_true - y_pred)**2)

def bce_jax(y_true, y_pred):
    eps = 1e-7
    y_pred = jnp.clip(y_pred, eps, 1 - eps)
    return -jnp.mean(y_true * jnp.log(y_pred) + (1 - y_true) * jnp.log(1 - y_pred))

start = time.time()
mse_jax_val = mse_jax(y_true_reg_jax, y_pred_reg_jax)
bce_jax_val = bce_jax(y_true_bin_jax, y_pred_bin_jax)
end = time.time()
print(f"JAX (CPU): MSE={mse_jax_val:.6f}, BCE={bce_jax_val:.6f}, tiempo={end - start:.6f} seg")

# JAX (GPU) si disponible
if any('gpu' in str(d).lower() for d in jax.devices()):
    y_true_reg_jax_gpu = jnp.array(y_true_reg)
    y_pred_reg_jax_gpu = jnp.array(y_pred_reg)
    y_true_bin_jax_gpu = jnp.array(y_true_bin)
    y_pred_bin_jax_gpu = jnp.array(y_pred_bin)
    # Calentamiento
    for _ in range(3):
        _ = mse_jax(y_true_reg_jax_gpu, y_pred_reg_jax_gpu)
        _ = bce_jax(y_true_bin_jax_gpu, y_pred_bin_jax_gpu)
    start = time.time()
    mse_jax_gpu = mse_jax(y_true_reg_jax_gpu, y_pred_reg_jax_gpu)
    bce_jax_gpu = bce_jax(y_true_bin_jax_gpu, y_pred_bin_jax_gpu)
    end = time.time()
    print(f"JAX (GPU): MSE={mse_jax_gpu:.6f}, BCE={bce_jax_gpu:.6f}, tiempo={end - start:.6f} seg")
else:
    print("JAX (GPU): no disponible")

Calculando pérdidas...
NumPy: MSE=1.981644, BCE=1.001598, tiempo=0.001096 seg
PyTorch (CPU): MSE=1.981645, BCE=1.001598, tiempo=0.003963 seg
PyTorch (GPU): MSE=1.981645, BCE=1.001598, tiempo=0.000139 seg
TensorFlow (CPU): MSE=1.981644, BCE=1.001598, tiempo=1.587746 seg
TensorFlow (GPU): MSE=1.981644, BCE=1.001598, tiempo=0.001615 seg
JAX (CPU): MSE=1.981645, BCE=1.001598, tiempo=0.410800 seg
JAX (GPU): no disponible


---
## Parte 4: Aplicaciones Adicionales

En esta sección exploraremos rápidamente cómo calcular similitud de coseno, distancias y kernel RBF usando tensores en los diferentes frameworks. Esto refuerza los conceptos de la Parte 4 del índice teórico.

In [11]:
# Datos: dos matrices de vectores (batch de embeddings)
np.random.seed(0)
emb1 = np.random.randn(5, 128).astype(np.float32)  # 5 vectores de 128-d
emb2 = np.random.randn(5, 128).astype(np.float32)

# ---- Similitud de coseno (por pares) ----
def cos_sim_np(a, b):
    a_norm = a / np.linalg.norm(a, axis=1, keepdims=True)
    b_norm = b / np.linalg.norm(b, axis=1, keepdims=True)
    return np.dot(a_norm, b_norm.T)

sim_np = cos_sim_np(emb1, emb2)
print("Similitud de coseno (NumPy):\n", sim_np)

# PyTorch
emb1_pt = torch.from_numpy(emb1)
emb2_pt = torch.from_numpy(emb2)
sim_pt = torch.cosine_similarity(emb1_pt.unsqueeze(1), emb2_pt.unsqueeze(0), dim=2)
print("Similitud de coseno (PyTorch):\n", sim_pt)

# TensorFlow
emb1_tf = tf.constant(emb1)
emb2_tf = tf.constant(emb2)
emb1_tf_norm = tf.nn.l2_normalize(emb1_tf, axis=1)
emb2_tf_norm = tf.nn.l2_normalize(emb2_tf, axis=1)
sim_tf = tf.matmul(emb1_tf_norm, emb2_tf_norm, transpose_b=True)
print("Similitud de coseno (TensorFlow):\n", sim_tf.numpy())

# JAX
emb1_jax = jnp.array(emb1)
emb2_jax = jnp.array(emb2)
emb1_jax_norm = emb1_jax / jnp.linalg.norm(emb1_jax, axis=1, keepdims=True)
emb2_jax_norm = emb2_jax / jnp.linalg.norm(emb2_jax, axis=1, keepdims=True)
sim_jax = jnp.dot(emb1_jax_norm, emb2_jax_norm.T)
print("Similitud de coseno (JAX):\n", sim_jax)

# ---- Distancia euclidiana ----
dist_np = np.linalg.norm(emb1[:, np.newaxis] - emb2, axis=2)
print("\nDistancia euclidiana (NumPy):\n", dist_np)

# ---- Kernel RBF ----
def rbf_kernel(X, Y, sigma=1.0):
    # X: (n, d), Y: (m, d) -> retorna (n, m)
    sq_dists = np.sum(X**2, axis=1, keepdims=True) + np.sum(Y**2, axis=1) - 2 * np.dot(X, Y.T)
    return np.exp(-sq_dists / (2 * sigma**2))

kernel_np = rbf_kernel(emb1, emb2)
print("\nKernel RBF (NumPy):\n", kernel_np)

Similitud de coseno (NumPy):
 [[-0.1299213  -0.08731853 -0.04454233  0.07057927  0.25715113]
 [-0.08057658  0.0103186  -0.08606823  0.05375465  0.06052087]
 [-0.15704344  0.09507892  0.02493378 -0.00598563 -0.09795401]
 [-0.00037486  0.03105928 -0.04941557  0.11721855 -0.06287164]
 [-0.11858218 -0.06080328 -0.09680887 -0.08891313 -0.08511013]]
Similitud de coseno (PyTorch):
 tensor([[-0.1299, -0.0873, -0.0445,  0.0706,  0.2572],
        [-0.0806,  0.0103, -0.0861,  0.0538,  0.0605],
        [-0.1570,  0.0951,  0.0249, -0.0060, -0.0980],
        [-0.0004,  0.0311, -0.0494,  0.1172, -0.0629],
        [-0.1186, -0.0608, -0.0968, -0.0889, -0.0851]])
Similitud de coseno (TensorFlow):
 [[-0.12992132 -0.08731854 -0.04454234  0.07057924  0.25715113]
 [-0.08057659  0.0103186  -0.08606823  0.05375467  0.06052087]
 [-0.15704347  0.09507889  0.02493378 -0.00598563 -0.09795403]
 [-0.00037485  0.03105928 -0.04941558  0.11721854 -0.06287163]
 [-0.11858218 -0.06080328 -0.09680887 -0.08891313 -0.085110

---
## Conclusiones

*   Hemos visto que **NumPy**, **PyTorch**, **TensorFlow** y **JAX** permiten realizar las mismas operaciones matemáticas fundamentales, pero con diferentes sintaxis y convenciones.
*   La **aceleración por GPU** es crucial para operaciones con grandes volúmenes de datos, como la multiplicación de matrices o el procesamiento de lotes en redes neuronales. En las pruebas, la GPU suele ser entre 10 y 50 veces más rápida que la CPU.
*   PyTorch y TensorFlow ofrecen funciones de alto nivel para activaciones y pérdidas, mientras que JAX requiere definir las funciones explícitamente (aunque también tiene `jax.nn`).
*   La elección del framework depende del proyecto, la comunidad, la facilidad de uso y el rendimiento. Todos son excelentes opciones para desarrollar modelos de IA.

¡Felicidades! Has dado un paso importante hacia la comprensión práctica de las herramientas que utilizarás en machine learning y deep learning.